name: Pull Request Review

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'chains/**'
      - 'explorer'
      - 'logos/**'
      - '.github/workflows/**'
      - '.gitmodules'
      - 'README.md'

permissions:
  contents: read
  pull-requests: read

jobs:
  config-check:
    name: Check blockchain configs
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Latest
        uses: actions/checkout@v4

      - name: Check Chain Configs
        uses: ping-pub/ping-dashboard-config-checker@v1.0

  build:
    name: Build explorer
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Latest
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: explorer/yarn.lock

      - name: Setup config
        run: cp -rf chains/* explorer/chains/

      - name: Install dependencies
        working-directory: explorer
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: explorer
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
